stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: /nifi-rel-nifi-1.7.0/nifi-docker/dockerhub/Dockerfile
      buildContext: .
      tag: draco-from-source-code
      pushRemote: true
      registry: 192.168.100.176:5000
timeout: 60
notification: {}
