stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: /nifi-rel-nifi-1.7.0/nifi-docker/dockerhub/Dockerfile
      buildContext: .
      tag: draco-from-source-code
      registry: 192.168.100.176:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
timeout: 60
notification: {}
