apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: draco
  namespace: fiware  
spec:
  replicas: 3
  template:
   metadata:
     labels:
       name: draco
   spec:
     containers:
     - name: draconifi
       image: csp2-centos-1:5000/draco-devops-image-new
       ports:
       - containerPort: 9090
       - containerPort: 5050
       - containerPort: 6060
---

apiVersion: v1
kind: Service
metadata:
  name: draco-service
  namespace: fiware
  labels:
    name: draco
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 31333
      name: data
    - port: 5050
      nodePort: 31344
      name: http
  selector:
    name: draco
